/*
  WHY THIS FILE EXISTS:
  HomePage is the route-level component for `/`. It composes HeroBanner and
  the genre MovieRows — it has no state or data fetching of its own.

  Route-level components act as "page directors": they decide what appears
  on the page and in what order, but delegate all rendering and data concerns
  to the components they compose.

  The genre rows are generated by mapping over the MOVIE_GENRES constant
  (defined in src/api/movies.ts) so adding or reordering genres requires
  changing only that one array.
*/

import { HeroBanner } from '../components/features/HeroBanner'
import { MovieRow } from '../components/features/MovieRow'
import { NavBar } from '../components/features/NavBar'
import { Footer } from '../components/features/Footer'
import { getTrendingTV } from '../api/tv'
import { getMoviesByGenre, getTrendingMovies, MOVIE_GENRES } from '../api/movies'

export function HomePage() {
  return (
    <>
      <NavBar />
      <main>
        <HeroBanner />

        {/* Negative margin pulls the rows up to overlap the hero gradient */}
        <div className="-mt-16 relative z-10 pb-12">
          {/* Trending Now row — uses the same query as HeroBanner, so it's cached */}
          <MovieRow
            label="Trending Now"
            queryKey={['trending', 'movies']}
            queryFn={getTrendingMovies}
          />

          {/* Trending TV — a separate resource type */}
          <MovieRow
            label="Trending TV Shows"
            queryKey={['trending', 'tv']}
            queryFn={getTrendingTV}
          />

          {/* Genre rows — one per entry in MOVIE_GENRES */}
          {MOVIE_GENRES.map((genre) => (
            <MovieRow
              key={genre.id}
              label={genre.label}
              queryKey={['movies', 'genre', String(genre.id)]}
              queryFn={() => getMoviesByGenre(genre.id)}
            />
          ))}
        </div>
      </main>
      <Footer />
    </>
  )
}
